%-----------------------------------------------------------------------
% Job configuration created by cfg_util (rev $Rev: 4252 $)
%-----------------------------------------------------------------------
%%
matlabbatch{1}.spm.temporal.st.scans = {
                                        {
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,1'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,2'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,3'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,4'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,5'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,6'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,7'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,8'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,9'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,10'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,11'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,12'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,13'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,14'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,15'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,16'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,17'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,18'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,19'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,20'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,21'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,22'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,23'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,24'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,25'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,26'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,27'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,28'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,29'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,30'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,31'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,32'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,33'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,34'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,35'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,36'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,37'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,38'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,39'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,40'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,41'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,42'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,43'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,44'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,45'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,46'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,47'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,48'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,49'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,50'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,51'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,52'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,53'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,54'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,55'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,56'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,57'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,58'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,59'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,60'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,61'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,62'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,63'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,64'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,65'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,66'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,67'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,68'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,69'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,70'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,71'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,72'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,73'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,74'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,75'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,76'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,77'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,78'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,79'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,80'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,81'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,82'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,83'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,84'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,85'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,86'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,87'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,88'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,89'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,90'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,91'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,92'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,93'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,94'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,95'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,96'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,97'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,98'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,99'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,100'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,101'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,102'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,103'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,104'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,105'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,106'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,107'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,108'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,109'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,110'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,111'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,112'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,113'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,114'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,115'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,116'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,117'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,118'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,119'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,120'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,121'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,122'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,123'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,124'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,125'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,126'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,127'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,128'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,129'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,130'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,131'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,132'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,133'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,134'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,135'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,136'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,137'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,138'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,139'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,140'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,141'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,142'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,143'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,144'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,145'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,146'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,147'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,148'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,149'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,150'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,151'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,152'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,153'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,154'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,155'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,156'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,157'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,158'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,159'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,160'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,161'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,162'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,163'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,164'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,165'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,166'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,167'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,168'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,169'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,170'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,171'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,172'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,173'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,174'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,175'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,176'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,177'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,178'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,179'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,180'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,181'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,182'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,183'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,184'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,185'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,186'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,187'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,188'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,189'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,190'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,191'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,192'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,193'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,194'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,195'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,196'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,197'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,198'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,199'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,200'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,201'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,202'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,203'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,204'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,205'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,206'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,207'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,208'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,209'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,210'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,211'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,212'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,213'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,214'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,215'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,216'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,217'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,218'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,219'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,220'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,221'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,222'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,223'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,224'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,225'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,226'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,227'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,228'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,229'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,230'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,231'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,232'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,233'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,234'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,235'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,236'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,237'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,238'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,239'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,240'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,241'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,242'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,243'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,244'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,245'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,246'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,247'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,248'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,249'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,250'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,251'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,252'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,253'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,254'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,255'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,256'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,257'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,258'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,259'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,260'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,261'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,262'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,263'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,264'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,265'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,266'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,267'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,268'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,269'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,270'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,271'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,272'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,273'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,274'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,275'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,276'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,277'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,278'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,279'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,280'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,281'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,282'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,283'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,284'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,285'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,286'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,287'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,288'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,289'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,290'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,291'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,292'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,293'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,294'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,295'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,296'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,297'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,298'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,299'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,300'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,301'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,302'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,303'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,304'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,305'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,306'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,307'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,308'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,309'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,310'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,311'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,312'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,313'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,314'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,315'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,316'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,317'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,318'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,319'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,320'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,321'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,322'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,323'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,324'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,325'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,326'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,327'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,328'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,329'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,330'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,331'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,332'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,333'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,334'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,335'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,336'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,337'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,338'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,339'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,340'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,341'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,342'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,343'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,344'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,345'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,346'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,347'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,348'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,349'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,350'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,351'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,352'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,353'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,354'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,355'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,356'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,357'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,358'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,359'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,360'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,361'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,362'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,363'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,364'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,365'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,366'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,367'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,368'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,369'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,370'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,371'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,372'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,373'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,374'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,375'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,376'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,377'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,378'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,379'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,380'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,381'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,382'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,383'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,384'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,385'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,386'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,387'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,388'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,389'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,390'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,391'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,392'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,393'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,394'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,395'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,396'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,397'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,398'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,399'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,400'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,401'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,402'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,403'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,404'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,405'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,406'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,407'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,408'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,409'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,410'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,411'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,412'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,413'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,414'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,415'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,416'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,417'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,418'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,419'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,420'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,421'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,422'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,423'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,424'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,425'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,426'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,427'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,428'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,429'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,430'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,431'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,432'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,433'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,434'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,435'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,436'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,437'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,438'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,439'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,440'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,441'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,442'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,443'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,444'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,445'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,446'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,447'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,448'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,449'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,450'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,451'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,452'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,453'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,454'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,455'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,456'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,457'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,458'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,459'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,460'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,461'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,462'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,463'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,464'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,465'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,466'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,467'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,468'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,469'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,470'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,471'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,472'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,473'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,474'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,475'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,476'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,477'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,478'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,479'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,480'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,481'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,482'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,483'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,484'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,485'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,486'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,487'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,488'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,489'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,490'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,491'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,492'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,493'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,494'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,495'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,496'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,497'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,498'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,499'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,500'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,501'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,502'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,503'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,504'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,505'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,506'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,507'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,508'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,509'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,510'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,511'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,512'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,513'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,514'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,515'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,516'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,517'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,518'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,519'
                                        '/home/klips/Documents/Eye_Tracking/first_level/ET002/epi/faceOM/ET002_ep2d_faceOM.nii,520'
                                        }
                                        }';
%%
matlabbatch{1}.spm.temporal.st.nslices = 33;
matlabbatch{1}.spm.temporal.st.tr = 2;
matlabbatch{1}.spm.temporal.st.ta = 1.93939393939394;
matlabbatch{1}.spm.temporal.st.so = [33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1];
matlabbatch{1}.spm.temporal.st.refslice = 17;
matlabbatch{1}.spm.temporal.st.prefix = 'a';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1) = cfg_dep;
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).tname = 'Session';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).sname = 'Slice Timing: Slice Timing Corr. Images (Sess 1)';
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).src_exbranch = substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{2}.spm.spatial.realign.estwrite.data{1}(1).src_output = substruct('()',{1}, '.','files');
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.sep = 4;
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.fwhm = 5;
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.rtm = 0;
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.interp = 7;
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.wrap = [0 1 0];
matlabbatch{2}.spm.spatial.realign.estwrite.eoptions.weight = {''};
matlabbatch{2}.spm.spatial.realign.estwrite.roptions.which = [0 1];
matlabbatch{2}.spm.spatial.realign.estwrite.roptions.interp = 7;
matlabbatch{2}.spm.spatial.realign.estwrite.roptions.wrap = [0 1 0];
matlabbatch{2}.spm.spatial.realign.estwrite.roptions.mask = 1;
matlabbatch{2}.spm.spatial.realign.estwrite.roptions.prefix = 'r';
matlabbatch{3}.spm.spatial.coreg.estimate.ref = {'/home/klips/Documents/Eye_Tracking/first_level/ET002/mprage/ET002_t1_mpr_ns_sag_iPAT.nii,1'};
matlabbatch{3}.spm.spatial.coreg.estimate.source(1) = cfg_dep;
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).tname = 'Source Image';
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).tgt_spec{1}(1).value = 'image';
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).tgt_spec{1}(2).value = 'e';
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).sname = 'Realign: Estimate & Reslice: Mean Image';
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).src_exbranch = substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{3}.spm.spatial.coreg.estimate.source(1).src_output = substruct('.','rmean');
matlabbatch{3}.spm.spatial.coreg.estimate.other(1) = cfg_dep;
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).tname = 'Other Images';
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).tgt_spec{1}(1).value = 'image';
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).tgt_spec{1}(2).value = 'e';
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).sname = 'Realign: Estimate & Reslice: Realigned Images (Sess 1)';
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).src_exbranch = substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{3}.spm.spatial.coreg.estimate.other(1).src_output = substruct('.','sess', '()',{1}, '.','cfiles');
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{3}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];
matlabbatch{4}.spm.spatial.preproc.data = {'/home/klips/Documents/Eye_Tracking/first_level/ET002/mprage/ET002_t1_mpr_ns_sag_iPAT.nii,1'};
matlabbatch{4}.spm.spatial.preproc.output.GM = [0 0 1];
matlabbatch{4}.spm.spatial.preproc.output.WM = [0 0 1];
matlabbatch{4}.spm.spatial.preproc.output.CSF = [0 0 0];
matlabbatch{4}.spm.spatial.preproc.output.biascor = 1;
matlabbatch{4}.spm.spatial.preproc.output.cleanup = 0;
matlabbatch{4}.spm.spatial.preproc.opts.tpm = {
                                               '/usr/local/spm8/tpm/csf.nii,1'
                                               '/usr/local/spm8/tpm/grey.nii,1'
                                               '/usr/local/spm8/tpm/white.nii,1'
                                               };
matlabbatch{4}.spm.spatial.preproc.opts.ngaus = [2
                                                 2
                                                 2
                                                 4];
matlabbatch{4}.spm.spatial.preproc.opts.regtype = 'mni';
matlabbatch{4}.spm.spatial.preproc.opts.warpreg = 1;
matlabbatch{4}.spm.spatial.preproc.opts.warpco = 25;
matlabbatch{4}.spm.spatial.preproc.opts.biasreg = 0.0001;
matlabbatch{4}.spm.spatial.preproc.opts.biasfwhm = 60;
matlabbatch{4}.spm.spatial.preproc.opts.samp = 3;
matlabbatch{4}.spm.spatial.preproc.opts.msk = {''};
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1) = cfg_dep;
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).tname = 'Parameter File';
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).tgt_spec{1}(1).value = 'mat';
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).tgt_spec{1}(2).value = 'e';
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).sname = 'Segment: Norm Params Subj->MNI';
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).src_exbranch = substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{5}.spm.spatial.normalise.write.subj.matname(1).src_output = substruct('()',{1}, '.','snfile', '()',{':'});
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1) = cfg_dep;
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).tname = 'Images to Write';
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).tgt_spec{1}(1).value = 'image';
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).tgt_spec{1}(2).value = 'e';
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).sname = 'Coregister: Estimate: Coregistered Images';
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).src_exbranch = substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{5}.spm.spatial.normalise.write.subj.resample(1).src_output = substruct('.','cfiles');
matlabbatch{5}.spm.spatial.normalise.write.roptions.preserve = 0;
matlabbatch{5}.spm.spatial.normalise.write.roptions.bb = [-78 -112 -50
                                                          78 76 85];
matlabbatch{5}.spm.spatial.normalise.write.roptions.vox = [3 3 3];
matlabbatch{5}.spm.spatial.normalise.write.roptions.interp = 7;
matlabbatch{5}.spm.spatial.normalise.write.roptions.wrap = [0 0 0];
matlabbatch{5}.spm.spatial.normalise.write.roptions.prefix = 'w';
matlabbatch{6}.spm.spatial.smooth.data(1) = cfg_dep;
matlabbatch{6}.spm.spatial.smooth.data(1).tname = 'Images to Smooth';
matlabbatch{6}.spm.spatial.smooth.data(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{6}.spm.spatial.smooth.data(1).tgt_spec{1}(1).value = 'image';
matlabbatch{6}.spm.spatial.smooth.data(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{6}.spm.spatial.smooth.data(1).tgt_spec{1}(2).value = 'e';
matlabbatch{6}.spm.spatial.smooth.data(1).sname = 'Normalise: Write: Normalised Images (Subj 1)';
matlabbatch{6}.spm.spatial.smooth.data(1).src_exbranch = substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{6}.spm.spatial.smooth.data(1).src_output = substruct('()',{1}, '.','files');
matlabbatch{6}.spm.spatial.smooth.fwhm = [6 6 6];
matlabbatch{6}.spm.spatial.smooth.dtype = 0;
matlabbatch{6}.spm.spatial.smooth.im = 0;
matlabbatch{6}.spm.spatial.smooth.prefix = 's';
